### ISSUE TITLE
Why the  column dimension of h_x is 12, not 23 ?

### ISSUE THREAD

**Issue by narutojxl** [hku-mars/IKFoM#21]
Hello everyone,
* In fast-lio state  x = [P, Q, delta_R, delta_t, V, bg, ba, g^w],  the measurement z is point-to-plane. So the jacobin of measurement  h_x dimension is 1 * 23 for one  laser point.  We can get it's expression like this:
![image](https://github.com/user-attachments/assets/83ef8677-8280-4f38-8e73-3ce20a8ba819)
 *  Why in the code, h_x dimension is 1 *12 for one laser point, [code link is here](https://github.com/hku-mars/FAST_LIO/blob/7cc4175de6f8ba2edf34bab02a42195b141027e9/src/laserMapping.cpp#L719-L721) .
  * What's the meaning of these 12 variables respectively? I want to add wheel odom velocity residual into estimator to joint optimize.  Thanks in advance for your help !

**Comment by narutojxl** [comment]
The 12 is  [P, Q, delta_R, delta_t] according to [this  code](https://github.com/hku-mars/FAST_LIO/blob/7cc4175de6f8ba2edf34bab02a42195b141027e9/src/laserMapping.cpp#L740-L744), close it now!

**Comment by narutojxl** [comment]
The 12 is  [P, Q, delta_R, delta_t] according to [this  code](https://github.com/hku-mars/FAST_LIO/blob/7cc4175de6f8ba2edf34bab02a42195b141027e9/src/laserMapping.cpp#L740-L744), close it now!

**Comment by zhh2005757** [comment]
h_x there is handled only for its first 12 dimensions aka pos and rotation, while the other dimensions are handled in update function, you can check it by reading codes of [esekfom.hpp](https://github.com/hku-mars/FAST_LIO/blob/7cc4175de6f8ba2edf34bab02a42195b141027e9/include/IKFoM_toolkit/esekfom/esekfom.hpp). As for wheel velocity fusion, you can refer to my repo [FAST-LIO-Multi-Sensor-Fusion](https://github.com/zhh2005757/FAST-LIO-Multi-Sensor-Fusion). For the states' meaning, there are a lot of blogs in websites for your learning since that is just common knowledge.
